version: "3.4"

services:
    voice-assisstant:
        container_name: voice-assisstant
        restart: always
        build:
            context: ./
            dockerfile: ./Dockerfile
        ports:
            - "8001:8000"

networks:
    default:
      name: voice-assisstant
